# Generated by Django 4.1.7 on 2023-02-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='availabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
