# Generated by Django 4.1.7 on 2023-02-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_interview_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='id',
            new_name='interview_id',
        ),
    ]
