# Generated by Django 4.1.7 on 2023-02-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_id_interview_interview_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
